title: "Philosophy of AI Quiz"
description: "A quiz on the definitions, history, and foundations of AI."
theme: jekyll-theme-primer
# If your repo name is 'philosophy-ai-quiz', set baseurl to '/philosophy-ai-quiz'
# If you are using 'username.github.io' as the repo name, leave baseurl empty ""
baseurl: "/philosophy-ai-quiz" 
url: "https://yourusername.github.io"
